name: octoo-static
runtime: yaml
description: OCTOO Svelte Skeleton Static AWS deployment
# Import the program's configuration settings.
config:
  errorDocument:
    type: string
    default: error.html
  indexDocument:
    type: string
    default: index.html
  path:
    type: string
    default: ../build
  domain:
    type: string
# Export the URLs and hostnames of the bucket and distribution.
outputs:
  websiteURL: ${web.websiteURL}
resources:
  zone:
    type: aws:route53/zone:Zone
    properties:
      name: ${domain}.
  web:
    type: "aws-static-website:index:Website"
    properties:
      sitePath: ${path}
      withCDN: true
      targetDomain: ${domain}
      withLogs: true,
      cacheTTL: 3600
